import = ["/home/carlos/.config/alacritty/colors.toml", "/home/carlos/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "Buttonless"
dynamic_title = true
startup_mode = "Windowed"
opacity = 0.95
blur = true


[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 12
y = 12
